# tasks file for 6581
- name: resoconto in file {{ logfile }}
  shell: echo "Applicato il bug {{bug}} dall'utente $USER in data $(date +%d-%m-%Y_%H:%M:%S) sui server {{inventory_hostname}} " >> {{ logfile }}
  delegate_to: localhost
  changed_when: false
- name: resoconto in database ansible
  shell: mysql --user=ansible_update --password=$(cat /home/password_insert) -e "insert into ansible.bugs values ( '{{bug}}','$USER','$(date +%d-%m-%Y_%H:%M:%S)','{{inventory_hostname}}');"
  delegate_to: localhost
  changed_when: false

- name: controllo raggiungibilità .saas.priv
  include: include/saaspriv.yml
  when: inventory_hostname[0:2] == "fw" or inventory_hostname[0:4] == "saas"

- name: "Determino quante istanze di mysql sono presenti sul server {{ inventory_hostname }}"
  shell: ls -1d /opt/mysql*
  changed_when: false
  check_mode: false
  failed_when: false
  register: istanze_mysql

- include: include/aggiorna_istanza.yml
  with_items:
  - "{{ istanze_mysql.stdout_lines }}"

# Adesso posso caricare direttamente a runtime il plugin
- name: carico il plugin a runtime per l'istanza mysql
  shell: mysql -e "INSTALL PLUGIN server_audit SONAME 'server_audit.so';"

- name: recupero il riferimento per eventuali altri istanze mysql
  shell: ls -1 /usr/bin/mysql[0-9][0-9]
  # qui facciamo l'ipotesi forte che le istanza mysql siano sempre del tipo mysql01 mysql02 mysql03 mysql04 ,....
  failed_when: false
  changed_when: false
  check_mode: false
  register: altri_mysql

- shell: "{{ item }} -e "INSTALL PLUGIN server_audit SONAME 'server_audit.so';""
  with_items:
  - "{{ altri_mysql.stdout_lines }}"

# configura syslog per 
- include: include/syslog.yml
