- debug: msg="Sto aggiornando l'istanza {{ item }}"

- name: "Controllo se l'istanza {{ item }} è una mysql 5.5"
  shell: "grep version= {{ item }}/install/mysql/bin/mysql_config | grep "5.5.30" "
  failed_when: false
  changed_when: false
  check_mode: false
  register: versione_corretta

- block:
  - name: "Copio il file server_audit.so in {{ item }}/install/mysql/lib/plugin/"
    copy:
     owner: root
     group: root
     mode: 0644
     src: files/server_audit.so
     dest: "{{ item }}/install/mysql/lib/plugin/"
  - include: include/conf_mysql.yml   

  when: versione_corretta.rc == 0
