- debug: msg="Sto aggiornando l'istanza {{ item }}"

- name: "Controllo se l'istanza {{ item }} è una mysql 5.5"
  shell: "grep version= {{ item }}/install/mysql/bin/mysql_config"
  failed_when: false
  changed_when: false
  check_mode: false
  register: versione_corretta

- stat: path="{{ item }}/bin/mariadb_config"
  register: mariadb

- block:
  - name: "Copio il file server_audit.so in {{ item }}/install/mysql/lib/plugin/"
    copy:
     owner: root
     group: root
     mode: 0644
     src: files/server_audit.so
     dest: "{{ item }}/install/mysql/lib/plugin/"
    when: ansible_distribution  == 'CentOS' and ansible_distribution_major_version == "7"
    
  - name: "Copio il file server_audit.so in {{ item }}/install/mysql/lib/plugin/"
    copy:
     owner: root
     group: root
     mode: 0644
     src: files/server_audit_rhel6.so
     dest: "{{ item }}/install/mysql/lib/plugin/server_audit.so"
    when: ansible_distribution_major_version == "6"  

  - include: include/conf_mysql.yml

  when:
  - versione_corretta.stdout.find('5.5.') != -1
  - mariadb.stat.exists == false
