- name: "Posiziono il file di configurazione syslog per produrre le loggate localmente nel file /var/log/audit_mysql"
  template:
    src: files/syslog_local.j2
    dest: /etc/rsyslog.d/audit_mysql.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_syslog
  when: syslog_nuovo.stat.exists
  
  
- name: "Posiziono il file di configurazione syslog per produrre le loggate localmente nel file /var/log/audit_mysql"
  lineinfile:
      path: /etc/syslog.conf
      backup: true
      line: "local1.info         /var/log/audit_mysql.log"
  notify: restart_syslog
  when: syslog_nuovo.stat.exists == false

- name: posiziono il file di rotate /etc/logrotate.d/audit_mysql
  copy:
    backup: true
    src: files/logrotate_local
    dest: /etc/logrotate.d/audit_mysql
    owner: root
    group: root
    mode: 0644
