- name: "Posiziono il file di configurazione syslog per spedire le loggate a {{ logserver_fastweb }} in /etc/rsyslog.d/audit_mysql.conf"
  template:
    src: files/syslog_fastweb.j2
    dest: /etc/rsyslog.d/audit_mysql.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_syslog
  when: syslog_nuovo.stat.exists
  
# Se siamo in presenza di una struttura vecchia di syslog (cioè solo confile /etc/syslog.conf), devo inserire la riga in syslog.conf  
- name:
  lineinfile:
    path: /etc/syslog.conf
    backup: true
    line: "local1.info             {{ logserver_fastweb_proto }}{{ logserver_fastweb }}"
  notify: restart_syslog
  when: syslog_nuovo.stat.exists == false  